import { createNextConfig } from '@bratislava/eslint-config-next'

export default [
  ...createNextConfig({
    ignores: [
      // Generated by Payload, don't edit
      'src/app/(payload)/**',
      'src/payload-types.ts',
      'src/payload-generated-schema.ts',
      'src/migrations/**',
    ],
  }),
  // https://github.com/bratislava/eslint-config/blob/master/packages/next/README.md#tailwind-css
  {
    settings: {
      'better-tailwindcss': {
        entryPoint: './src/app/(frontend)/globals.css',
        callees: ['cx', 'classnames', 'clsx', 'cn', 'twMerge', 'tw'],
      },
    },
  },
  // Project-specific rule overrides
  {
    rules: {
      'no-multi-spaces': 'error',
      'i18next/no-literal-string': 'off',
    },
  },
]
